paths:
  save_path: "/content/sample_data"
  data_path: "/content/drive/MyDrive/Master_Thesis/train_data/T5_training/train_test_q_pa"
optim:
  lr: 1.0e-3
  weight_decay: 0.05
  warmup_steps: 1000
  total_steps: null
  final_cosine: 1.0e-5
train:
  batch_size: 15
  epochs: 1
  grad_acc_steps: 4
  log_steps: 40
eval:
  batch_size: 20
model:
  path: "t5-base"
  sep_token: "<sep>"